version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '6606:3306'
    volumes:
      - my-db:/var/lib/mysql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6385:6379'
    volumes:
      - cache:/data

volumes:
  my-db:
  cache:
